### ISSUE TITLE
CIEDE2000 speed

### ISSUE THREAD

**Issue by leeoniya** [pmav/picbit#1]
hey @pmav, quick question.

Were you able to get decent performance out of CIEDE2000? i just tried implementing it in `RgbQuant.js` using a tweaked version of https://github.com/markusn/color-diff and 'slow as hell' doesn't even begin to describe it. see the branch here: https://github.com/leeoniya/RgbQuant.js/tree/ciede2000. Looks like i'll be sticking with the component-scaled Euclidean distance into the foreseeable future.

thoughts?

Also, I just published v1.1.0 of RgbQuant with some good perf improvements thanks to a better caching strategy.

thanks,
Leon

**Comment by pmav** [comment]
Hi!
I will take a look later today. It's strange because I use the exact same
code, with some exceptions:
- Moved the functions: hp_f, dhp_f,  a_hp_f out of the main function

**Comment by pmav** [comment]
The function colorDist in the following code is being called 256 million times for a small image. I checked and the CIEDE2000 algorithm is just like the one I use...

``` javascript
// iterate palette
for (var i = 0; i < len; i++) {
    var pxi = idxrgb[i], i32i = idxi32[i];
    if (!pxi) continue;

    for (var j = i + 1; j < len; j++) {
        var pxj = idxrgb[j], i32j = idxi32[j];
        if (!pxj) continue;

        var dist = colorDist(pxi, pxj);

        if (dist < thold) {
            // store index,rgb,dist
            memDist.push([j, pxj, i32j, dist]);

            // kill squashed value
            delete(idxrgb[j]);
            palLen--;
        }
    }
}
```

**Comment by leeoniya** [comment]
uhhh, something is seriously wrong then. can you provide the image?

**Comment by pmav** [comment]
I used the fish_th,jpg and the fishie2_th.jpg I think.

Edit:
just a note - I don't know if the function is called exactly 256 million times (len x len), because of if(!pxi) and if(!pxj) but is called at least a few million times (that I checked with a counter :smile:)

**Comment by leeoniya** [comment]
that fish jpeg is probably the worst-case (has one of the largest histograms to reduce), lol. 250 million is pretty insane though. did you instrument the function with a counter to get that number? i know firefox and chrome wont give it to you cause they both use sampling profilers.

**Comment by pmav** [comment]
Yep, I just added some counters after some changes on the CIEDE2000 function and the rgb to lab (that had no effect at all).

**Comment by leeoniya** [comment]
now that i think of it, CIEDE2000 probably gives a much different color distance metric which completely borks the palette reduction ramping.

**Comment by leeoniya** [comment]
can you try running the master and see how many call counts you get?

edit: yeah, this is almost certainly the case. i just calc and return the raw distance. oops. https://github.com/leeoniya/RgbQuant.js/blob/ciede2000/src/rgbquant.js#L730

do you know off-hand what the max possible distance is? can i assume it's #000 - #fff ?

**Comment by pmav** [comment]
Around 57 150 000. If the CIEDE2000 is called the same number if times it will take forever...

**Comment by leeoniya** [comment]
ok, i'll investigate tonight. thanks.

**Comment by pmav** [comment]
Sure, no problem.
